baseURL: http://pranavmr.xyz/
title: "@pranavmr009"
paginate: 5
theme: charlolamode

menu:
  main:
    - name: About
      url: /About/
      weight: 30
    - name: Articles
      url: /articles/
      weight: 20
    - name: Projects
      url: /projects/
      weight: 15
    - name: Git
      url: https://git.pranavmr.xyz
      weight: 10

# - name: Categories
#   url: /categories/
#   weight: 10
# - name: new Tab
#   url: /newtab/
#   weight: defines order of tabs

params:
  author: Pranav MR

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: Pranav MR
    description: |
      Hello, I am Pranav.
      I am a cybersecurity enthusiast.

      I am really into the defensive side, like malware analysis and reversing.

    imageUrl: "/images/pranav.jpeg"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Don't click me
        url: https://www.youtube.com/@pranavtechy
  mainSections:
    - articles

  socialIcons:
    - name: github
      url: "https://github.com/pranavmr009"
    - name: linkedin
      url: "https://www.linkedin.com/in/pranavmr009/"
    - name: twitter
      url: "https://twitter.com/pranavmr009"
    - name: fiverr
      url: "https://www.fiverr.com/pranavtechy"
    - name: gmail
      url: "mailto:pranavtechy@protonmail.com"

# add more social icons. find more in svg.html file
# - name: youtube
#   url: yoururl
# - name: twitter
#   url: yoururl
# - name: facebook
#   url: yoururl

# change favicon in images folder (icon for web tab)
assets:
  favicon: "/images/terminal.png"
  favicon16x16: "/images/terminal.png"
  favicon32x32: "/images/terminal.png"
  apple_touch_icon: "/images/terminal.png"
  safari_pinned_tab: "/images/terminal.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
